[package]
name = "image_downloader"
version = "0.1.0"
authors = ["moparisthebest <admin@moparisthebest.com>"]

[dependencies]
rust-crypto = "0.2.36"
rustc-serialize = "0.3.24"
#rand = "^0.3"
#ring = "0.11.0"
